# Generated by Django 6.0 on 2025-12-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativearea',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
