# Generated by Django 6.0 on 2025-12-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_administrativearea_zip_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativearea',
            options={'ordering': ('zip_code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='administrativearea',
            unique_together={('name', 'zip_code')},
        ),
    ]
