# Generated by Django 6.0 on 2025-12-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_administrativearea_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='PA', max_length=10, verbose_name='State abbreviation')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('state', 'name'),
            },
        ),
        migrations.DeleteModel(
            name='AdministrativeArea',
        ),
        migrations.AlterModelOptions(
            name='responseunit',
            options={'ordering': ('responder_type', 'station_name')},
        ),
        migrations.AddField(
            model_name='emergencycall',
            name='zip_code',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='responseunit',
            unique_together={('responder_type', 'station_name')},
        ),
        migrations.AddField(
            model_name='emergencycall',
            name='township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.township'),
        ),
    ]
