# Generated by Django 6.0 on 2025-12-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_township_delete_administrativearea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='township',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
