# Generated by Django 6.0 on 2025-12-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_township_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='township',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='township',
            unique_together={('state', 'name')},
        ),
    ]
