# Generated by Django 6.0 on 2025-12-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_township_name_alter_township_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponderType',
            new_name='ResponseType',
        ),
        migrations.AlterModelOptions(
            name='responseunit',
            options={'ordering': ('response_type', 'station_name')},
        ),
        migrations.RenameField(
            model_name='responseunit',
            old_name='responder_type',
            new_name='response_type',
        ),
        migrations.AlterUniqueTogether(
            name='responseunit',
            unique_together={('response_type', 'station_name')},
        ),
    ]
