# Generated by Django 6.0 on 2025-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_respondertype_responsetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='responsetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
